export const SQUARE_MOUSE_DOWN_LEFT = 'SQUARE_MOUSE_DOWN_LEFT';
export const SQUARE_MOUSE_DOWN_RIGHT = 'SQUARE_MOUSE_DOWN_RIGHT';
export const SQUARE_MOUSE_UP_LEFT = 'SQUARE_MOUSE_UP_LEFT';
export const SQUARE_MOUSE_UP_RIGHT = 'SQUARE_MOUSE_UP_RIGHT';
export const SQUARE_MOUSE_LEAVE = 'SQUARE_MOUSE_LEAVE';
export const INIT_MATRIX = 'INIT_MATRIX';
