export const RESET_ACTIVE_SQUARE_COORDINATE = 'RESET_ACTIVE_SQUARE_COORDINATE';
export const SET_ACTIVE_SQUARE_COORDINATE = 'SET_ACTIVE_SQUARE_COORDINATE';
export const SET_MATRIX = 'SET_MATRIX';
export const SET_FAILED = 'SET_FAILED';
